### ISSUE TITLE
Support for node v14.20.0

### ISSUE THREAD

**Issue by emiller12** [mysense-ai/ServerlessPlugin-SSMPublish#137]
Hello, with the release of node v14.20.0 on the 7th of July this package is now causing the following error in our project when installing dependencies:

```
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error serverless-ssm-publish@1.4.2: The engine "node" is incompatible with this module. Expected version ">=10.0.0 <=14.19.3". Got "14.20.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

This due to the following restriction currently in the `package.json`

```
"engines": {
    "node": ">=10.0.0 <=14.19.3",
    "npm": ">=6.13.1 <=6.14.7"
  }
```

Would it be possible to bump this to allow use of this package with the latest version of node 14?

**Comment by chippyash** [comment]
npm WARN EBADENGINE Unsupported engine {                                                                                                       
npm WARN EBADENGINE   package: 'serverless-ssm-publish-plugin@1.3.2',                                                                          
npm WARN EBADENGINE   required: { node: '>=10.0.0', npm: '6.13.1' },                                                                           
npm WARN EBADENGINE   current: { node: 'v14.17.1', npm: '8.12.1' }                                                                             
npm WARN EBADENGINE }
