### ISSUE TITLE
Support for node v14.x.x or 16.x.x

### ISSUE THREAD

**Issue by oieduardorabelo** [mysense-ai/ServerlessPlugin-SSMPublish#138]
hello there 👋 

we have multiple projects using different Node versions, from 14.x to 16.x

any plans to update the engine fields in package json to support it?

```json
"engines": {
  "node": ">=10.0.0 <=14.19.3",
  "npm": ">=6.13.1 <=6.14.7"
}
```

In projects where we use node 16.x, we are also using `serverless-esbuild` it expects the latest version of Node:

```bash
serverless-esbuild@1.33.0: The engine "node" is incompatible with this module. Expected version ">=16.0.0". Got "14.19.3"
```

adding more flexibility in the engine fields in SSMPublish would help us create a standard across our projects,
thank you!

**Comment by cloudwitch** [comment]
Found this error as well.  I will most likely end up replacing this with Cloudformation.

**Comment by cloudwitch** [comment]
Works with node 16 even though it throws that warning.  I was expecting to have to switch this to Cloudformation.

Would be nice to get an update though.

Thanks for the hard work!
