### ISSUE TITLE
Support for Node > 16.8

### ISSUE THREAD

**Issue by davidjb** [mysense-ai/ServerlessPlugin-SSMPublish#143]
Currently the `engines` configuration within `package.json` restricts installation on Node version to between 14 and 16.8.1. The most recent release in the 16.x line is 16.19.0 and isn't compatible with this package. Likewise, the current LTS release is 18.x.x and latest release is 19.x.x. Overriding the `engines` configuration on Node 19 allows the install and things seem okay.

Could the supported Node versions be adjusted and/or would it be feasible to make them less restrictive in general?

Thanks in advance!

**Comment by KillDozerX2** [comment]
We could also this, our team is migrating to node 18 soon and we use this plugin.

**Comment by Dhruminthkk** [comment]
+1

**Comment by devanshutanna** [comment]
+1

**Comment by Jeeltilva** [comment]
+1

**Comment by tjdavey** [comment]
+1

**Comment by jonachehilton** [comment]
+1

**Comment by tjdavey** [comment]
+1
