### ISSUE TITLE
Add tags to definitions

### ISSUE THREAD

**Issue by chippyash** [mysense-ai/ServerlessPlugin-SSMPublish#66]
Tagging is a core technology within AWS for all sorts of activity: Billing, IAM, Lambda invocation rules etc.

Please consider adding tags to the definition for publishing SSM parameters, either by using provider tags + overrides or as with sqsTags, additional configuration items within the existing custom ssmPublish namespace

**Comment by ColdFire87** [comment]
PR https://github.com/mysense-ai/ServerlessPlugin-SSMPublish/pull/68 adds support for tags. Will merge it after the requested changes are pushed.

**Comment by chippyash** [comment]
Don't think Ravi is doing tags in that PR, just StringList. I believe it's complicated by the fact that adding/updating tags is a second operation after parameter is created/updated
